[env]
# don't automatically load `.env` files.
file = false

[install]
# never auto-install dependencies.
auto = false
# whether to set an exact version in `package.json`
exact = true
# bun install will not update `bun.lock`
frozenLockfile = true
# only install package versions published at least 1 days ago (in seconds)
minimumReleaseAge = 86400
